### PR TITLE
Utils

### PR DESCRIPTION
**Pull request by dcurrey88**
Updating docs in accordance with new "useful functions" added to cortex. In general this includes:

- Module scheduling code
- General code for common API calls
- Wrappers for interacting with activites and sensors
- Misc functions such as parsing participant phone type

### CODE REVIEW

**Comment by avaidyam** [comment]
Heads up: all file and folder names should be lowercase! And you technically shouldn't call it `README` if it's part of the docs website. 😅

**Comment by dcurrey88** [comment]
> Heads up: all file and folder names should be lowercase! And you technically shouldn't call it `README` if it's part of the docs website. 😅

I'll rename the folders in 06-cortex to be lowercase. What `README` are you referring to? I must have added the file by accident.

**Comment by avaidyam** [comment]
> `docs/09-data_science/06-Cortex/05-Features/02-Secondary/01-Readme.md`

**Comment by dcurrey88** [comment]
> > `docs/09-data_science/06-Cortex/05-Features/02-Secondary/01-Readme.md`

Good catch. I'll rename those.

**Pull request merged**
